const productos = [
    {
        nombre : "STORMTROOPER LIGHTSABER",
        licencia : "STAR WARS",
        descripcion : "Figura coleccionable de Stormtrooper Lightsaber - The Mandalorian Saga, edición limitada.",
        imagen : "../img/star-wars/trooper-1.webp",
        imagenCaja : "../img/star-wars/trooper-box.webp",
        imagenIndex : "./img/star-wars/trooper-1.webp",
        imagenCajaIndex : "./img/star-wars/trooper-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "PIDGEOTTO",
        licencia : "POKEMON",
        descripcion : "Figura coleccionable de Pidgeotto - Pokemon, edición limitada",
        imagen : "../img/pokemon/pidgeotto-1.webp",
        imagenCaja : "../img/pokemon/pidgeotto-box.webp",
        imagenIndex : "./img/pokemon/pidgeotto-1.webp",
        imagenCajaIndex : "./img/pokemon/pidgeotto-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "LUNA LOVEGOOD LION MASK",
        licencia : "HARRY POTTER",
        descripcion : "Figura coleccionable de Luna Lovegood Lion Mask - Harry Potter, edición limitada.",
        imagen : "../img/harry-potter/luna-1.webp",
        imagenCaja : "../img/harry-potter/luna-box.webp",
        imagenIndex : "./img/harry-potter/luna-1.webp",
        imagenCajaIndex : "./img/harry-potter/luna-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "BABY YODA BLUEBALL",
        licencia : "STAR WARS",
        descripcion : "Figura coleccionable de Baby Yoda (Grogu) - The Mandalorian Saga, edición limitada.",
        imagen : "../img/star-wars/baby-yoda-1.webp",
        imagenCaja : "../img/star-wars/baby-yoda-box.webp",
        imagenIndex : "./img/star-wars/baby-yoda-1.webp",
        imagenCajaIndex : "./img/star-wars/baby-yoda-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "VULPIX",
        licencia : "POKEMON",
        descripcion : "Figura coleccionable de Vulpix- Pokemon, edición limitada.",
        imagen : "../img/pokemon/vulpix-1.webp",
        imagenCaja : "../img/pokemon/vulpix-box.webp",
        imagenIndex : "./img/pokemon/vulpix-1.webp",
        imagenCajaIndex : "./img/pokemon/vulpix-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "SNAPE PATRONUS",
        licencia : "HARRY POTTER",
        descripcion : "Figura coleccionable de Snape Patronus - Harry Potter, edición limitada.",
        imagen : "../img/harry-potter/snape-patronus-1.webp",
        imagenCaja : "../img/harry-potter/snape-patronus-box.webp",
        imagenIndex : "./img/harry-potter/snape-patronus-1.webp",
        imagenCajaIndex : "./img/harry-potter/snape-patronus-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "KAKASHI HATAKE",
        licencia : "NARUTO",
        descripcion : "Figura coleccionable de Kakashi Hatake - Naruto, edición limitada.",
        imagen : "../img/naruto/kakashi-hatake.webp",
        imagenCaja : "../img/naruto/kakashi hatake-box.webp",
        imagenIndex : "./img/naruto/kakashi-hatake.webp",
        imagenCajaIndex : "./img/naruto/kakashi hatake-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "LUKE",
        licencia : "STAR WARS",
        descripcion : "Figura coleccionable de Luke - The Mandalorian Saga, edición limitada.",
        imagen : "../img/star-wars/luke-1.webp",
        imagenCaja : "../img/star-wars/luke-box.webp",
        imagenIndex : "./img/star-wars/luke-1.webp",
        imagenCajaIndex : "./img/star-wars/luke-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "CHARMANDER",
        licencia : "POKEMON",
        descripcion : "Figura coleccionable de Charmander- Pokemon, edición limitada.",
        imagen : "../img/pokemon/charmander-1.webp",
        imagenCaja : "../img/pokemon/charmander-box.webp",
        imagenIndex : "./img/pokemon/charmander-1.webp",
        imagenCajaIndex : "./img/pokemon/charmander-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "HERMIONE",
        licencia : "HARRY POTTER",
        descripcion : "Figura coleccionable de Hermione - Harry Potter, edición limitada.",
        imagen : "../img/harry-potter/hermione-1.webp",
        imagenCaja : "../img/harry-potter/hermione-box.webp",
        imagenIndex : "./img/harry-potter/hermione-1.webp",
        imagenCajaIndex : "./img/harry-potter/hermione-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "BOBBAFETH",
        licencia : "STAR WARS",
        descripcion : "Figura coleccionable de Bobbafeth - The Mandalorian Saga, edición limitada.",
        imagen : "../img/star-wars/bobbafeth-1.webp",
        imagenCaja : "../img/star-wars/bobbafeth-box.webp",
        imagenIndex : "./img/star-wars/bobbafeth-1.webp",
        imagenCajaIndex : "./img/star-wars/bobbafeth-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "PIKACHU",
        licencia : "POKEMON",
        descripcion : "Figura coleccionable de Pikachu- Pokemon, edición limitada.",
        imagen : "../img/pokemon/pikachu-1.webp",
        imagenCaja : "../img/pokemon/pikachu-box.webp",
        imagenIndex : "./img/pokemon/pikachu-1.webp",
        imagenCajaIndex : "./img/pokemon/pikachu-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "HARRY",
        licencia : "HARRY POTTER",
        descripcion : "Figura coleccionable de Harry - Harry Potter, edición limitada.",
        imagen : "../img/harry-potter/harry-1.webp",
        imagenCaja : "../img/harry-potter/harry-box.webp",
        imagenIndex : "./img/harry-potter/harry-1.webp",
        imagenCajaIndex : "./img/harry-potter/harry-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
    {
        nombre : "DRAGONITE",
        licencia : "POKEMON",
        descripcion : "Figura coleccionable de Dragonite- Pokemon, edición limitada.",
        imagen : "../img/pokemon/dragonite-1.webp",
        imagenCaja : "../img/pokemon/dragonite-box.webp",
        imagenIndex : "./img/pokemon/dragonite-1.webp",
        imagenCajaIndex : "./img/pokemon/dragonite-box.webp",
        precio : "$ 1799,99",
        cuotas : "3 CUOTAS SIN INTERÉS",
        tag : "Nuevo",
    },
];

export{
    productos,
}